### ISSUE TITLE
请问一下，可以针对所有的conv层生成CAM吗？

### ISSUE THREAD

**Issue by ACkuku** [ypwhs/CAM_gluon#1]

**Comment by ypwhs** [comment]
只有接了分类器才能进行 CAM 可视化，如果你希望对中间层进行可视化，可以使用 Grad-CAM。

参考链接：

* https://arxiv.org/abs/1610.02391
* https://github.com/ramprs/grad-cam
* https://github.com/jacobgil/keras-grad-cam
